### ISSUE TITLE
Argument 2 passed to SMW\ApprovedRevs\Hooks::onChangeRevision() must be an instance of Revision or null

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/SemanticApprovedRevs#27]
### Setup and configuration

- SMW version: 4.0.0
- AR: 1.7.3
- SAR version: 0.9.1
- MW version: 1.35
- DB (MySQL etc.): MySQL

### Issue

Produces an Internal Error on approve

```
[247416eeaad4471190c0c8c5] /index.php?title=Main_Page&action=approve&oldid=1 TypeError from line 172 of /var/www/html/extensions/SemanticApprovedRevs/src/Hooks.php: Argument 2 passed to SMW\ApprovedRevs\Hooks::onChangeRevision() must be an instance of Revision or null, instance of MediaWiki\Revision\RevisionStoreRecord given, called in /var/www/html/includes/HookContainer/HookContainer.php on line 329

Backtrace:

#0 /var/www/html/includes/HookContainer/HookContainer.php(329): SMW\ApprovedRevs\Hooks->onChangeRevision(Title, MediaWiki\Revision\RevisionStoreRecord)
#1 /var/www/html/includes/HookContainer/HookContainer.php(132): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
```

Steps to reproduce the observation:

- Vanilla Wiki with default Main Page
- Login as WikiSysop
- Approve "Main Page"

**Comment by gesinn-it-wam** [comment]
Reproduced the issue by a integration test: https://github.com/SemanticMediaWiki/SemanticApprovedRevs/runs/5551416471?check_suite_focus=true#step:10:155
